### ISSUE TITLE
Error in test

### ISSUE THREAD

**Issue by pablo1n7** [invertase/react-native-firebase-authentication-example#11]
Hi!. I can try to test the example with: 

npx react-native init ProjectName --template invertase/react-native-firebase-authentication-example

but the installation has an error: 

'error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/react-native-template-invertase/react-native-firebase-authentication-example.git
Directory: /Users/pablo/Documents/Codigo/ProjectName
Output:
ERROR: Repository not found.'

is Maybe?: 

'Arguments: ls-remote --tags --heads ssh://git@github.com/ ~~react-native-template-~~ invertase/react-native-firebase-authentication-example.git'

Thanks you

**Comment by mikehardy** [comment]
Bienvenidos desde Ecuador ;-) :wave: 

Hi there! I'm sorry, I cannot see any place where `react-native-template` is used in template config or package.json or anywhere? I am not sure where that is coming from

I just ran the command you included locally and it worked: `npx react-native init ProjectName --template invertase/react-native-firebase-authentication-example`

Perhaps you had a transient local network failure of some sort? I cannot reproduce the problem

![image](https://user-images.githubusercontent.com/782704/156037368-c635370d-e64d-441e-a08d-e988f5c43a9d.png)

**Comment by pablo1n7** [comment]
Hola! :) Desde Argentina, gracias por responder. 

when execute: 'npx react-native init ProjectName --template invertase/react-native-firebase-authentication-example':

`error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/react-native-template-invertase/react-native-firebase-authentication-example.git
Directory: /Users/pablo/Documents/Codigo/ProjectName
Output:
ERROR: Repository not found.
fatal: No se pudo leer del repositorio remoto.

Por favor asegúrate que tienes los permisos de acceso correctos
y que el repositorio existe.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn remove v1.22.10
warning ../package.json: No license field
[1/2] 🗑  Removing module react-native-template-invertase/react-native-firebase-authentication-example...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-invertase/react-native-firebase-authentication-example. This is not a critical error, you can work on your app.
/Users/pablo/Documents/Codigo/ProjectName/node_modules/metro-hermes-compiler/src/emhermesc.js:77
          throw ex;
          ^

RuntimeError: abort(Error: Command failed: yarn add react-native-template-invertase/react-native-firebase-authentication-example). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/Users/pablo/Documents/Codigo/ProjectName/node_modules/metro-hermes-compiler/src/emhermesc.js:440:13)
    at process.emit (events.js:314:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)`


The command fails in 'yarn add react-native-template-invertase/react-native-firebase-authentication-example'...

but when i run separately it works fine 'yarn add invertase/react-native-firebase-authentication-example' works fine.

**Comment by mikehardy** [comment]
I wonder if it has something to do with node version? Or git or ssh?

```
mike@bistromath:~ % npx --version
8.5.2
mike@bistromath:~ % node --version
v16.14.0
mike@bistromath:~ % git --version
git version 2.32.0
```

There must be something going on, but as I mentioned above, it works for me - without a reproduction I am not sure what is going on

**Comment by pablo1n7** [comment]
Thanks you, i changed the versions and worked!

gracias :)

**Comment by mikehardy** [comment]
Just out of curiosity, which version was it? I wasn't aware that we had restrictions in the version area on those tools so I'd love to know, then we could document or at least help people in the future. Glad you got it working though!

**Comment by pablo1n7** [comment]
old versions i had: 

node 12.22.7.

npx 6.14.15

git version 2.32.0

**Comment by mikehardy** [comment]
I'm going to reopen this with one focused goal (in case someone else wants to test it): see which one of those tool+version combos was the cause of the problem, so we can document it and/or add it to the react-native doctor checks (assuming they don't already verify)
